export const copywritingCategories = [
  {
    id: "news",
    number: "01",
    title: "新闻稿",
    en: "News Release",
    color: "#b9dc53",
    works: [
      { title: "重大数字记忆项目-李芳昱教授专访", src: "/assets/copywriting/news/digital-memory.webp" },
      { title: "重大“龙骨行动”基层实践活动新闻稿", src: "/assets/copywriting/news/youth-service.webp" },
      { title: "重大“成为更好的自己”系列主题讲座新闻稿", src: "/assets/copywriting/news/better-self.webp" },
    ],
  },
  {
    id: "planning",
    number: "02",
    title: "活动策划",
    en: "Campaign Planning",
    color: "#e89a82",
    works: [
      { title: "新闻传播学院元旦晚会活动策划案封面", src: "/assets/copywriting/planning/new-year-1.webp" },
      { title: "新闻传播学院元旦晚会活动策划案", src: "/assets/copywriting/planning/new-year-2.webp" },
      { title: "中小学生艺术活动月宣传片方案", src: "/assets/copywriting/planning/promo-plan.webp" },
      { title: "五一购车不踩坑｜懂车帝门店活动全案", src: "/assets/copywriting/planning/dongchedi-may.webp", protected: true },
      { title: "7月汽车下乡惠民季｜懂车帝新车团购会", src: "/assets/copywriting/planning/dongchedi-july.webp", protected: true },
      { title: "端午购车狂欢｜车展惠民专场", src: "/assets/copywriting/planning/dongchedi-auto-show.webp", protected: true },
      { title: "乘风破浪的SISUer综艺策划", src: "/assets/copywriting/planning/variety-1.webp" },
      { title: "电影时光会 综艺策划", src: "/assets/copywriting/planning/variety-2.webp" },
    ],
  },
  {
    id: "commentary",
    number: "03",
    title: "评论网宣",
    en: "Commentary",
    color: "#9bcbd4",
    works: [
      { title: "新闻评论封面", src: "/assets/copywriting/commentary/comment-cover.webp" },
      { title: "新闻评论", src: "/assets/copywriting/commentary/news-comment.webp" },
      { title: "网宣文章（一）", src: "/assets/copywriting/commentary/publicity-1.webp" },
      { title: "网宣文章（二）", src: "/assets/copywriting/commentary/publicity-2.webp" },
    ],
  },
  {
    id: "case-study",
    number: "04",
    title: "案例萃取",
    en: "Case Study",
    color: "#e4c75f",
    works: [
      { title: "网销专家AI人机协同作业中效能提升", src: "/assets/copywriting/case-study/ai-collaboration.webp", protected: true },
      { title: "网销专家金融产品渗透率提升实战技巧", src: "/assets/copywriting/case-study/finance-penetration.webp", protected: true },
      { title: "从筛线索到锁客到店：邀约全链路作业指引", src: "/assets/copywriting/case-study/lead-to-store.webp", protected: true },
    ],
  },
  {
    id: "transcript",
    number: "05",
    title: "解说词和串词",
    en: "Narration & Transcript",
    color: "#9fc9aa",
    works: [
      { title: "主持稿串词", src: "/assets/copywriting/transcript/host-script.webp" },
      { title: "纪录片解说词", src: "/assets/copywriting/transcript/documentary-narration.webp" },
    ],
  },
  {
    id: "scripts",
    number: "06",
    title: "剧本脚本",
    en: "Scripts",
    color: "#d7a0b6",
    works: [
      { title: "剧本《破茧》", src: "/assets/copywriting/scripts/cocoon.webp" },
      { title: "剧本《血中花》", src: "/assets/copywriting/scripts/blood-flower.webp" },
      { title: "短视频脚本《青春日记》", src: "/assets/copywriting/scripts/youth-diary.webp" },
      { title: "话剧直播脚本《明德秘史》", src: "/assets/copywriting/scripts/stage-live.webp" },
    ],
  },
];
